rentcrm/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rentcrm import views

admin.site.site_header = 'RentCRM administration'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^scripts/', include('scripts.urls')),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^', include('rentcrm.urls'))
]

rentcrm/rentcrm/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='apartments_all'),
    url(r'^free/$', views.free, name='apartments_free'),
    url(r'^moving-out/$', views.moving_out, name='apartments_moving_out'),
    url(r'^debitors/$', views.debitors, name='apartments_debt'),
    url(r'^renewal-required/$', views.renewal_required, name='apartments_renew'),
    url(r'^renewal-sent/$', views.renewal_sent, name='apartments_update'),
    url(r'^renewal-send-pastdue/$', views.renewal_send_pastdue, name='renewal_send_pastdue'),
    url(r'^renewal-pastdue/$', views.renewal_pastdue, name='renewal_pastdue'),

    url(r'^building/(?P<building_pk>[0-9]+)/$',
        views.building_apartments, name='building_apartments'),

    url(r'^apartments/(?P<apt_pk>[0-9]+)/$',
        views.cc_info, name='contract_info'),
    url(r'^contracts/(?P<contract_id>[0-9]+)/payments/$',
        views.contract_payments, name='contract_payments'),

    url(r'^apartments/(?P<apt_pk>[0-9]+)/send-renewal/$',
        views.send_renewal, name='send-renewal'),
    url(r'^apartments/(?P<apt_pk>[0-9]+)/update-lease/$',
        views.update_lease, name='update_lease'),
    url(r'^apartments/(?P<apt_pk>[0-9]+)/pay-in/$', views.pay_in, name='add_payment'),
    url(r'^apartments/(?P<apt_pk>[0-9]+)/adjust/$', views.rent_adjustment, name='rent_adjustment'),
    url(r'^apartments/(?P<apt_pk>[0-9]+)/start-lease/$',
        views.start_lease, name='start_lease'),
    url(r'^apartments/(?P<apt_pk>[0-9]+)/end-lease/$',
        views.end_lease, name='end_lease'),
    url(r'^apartments/(?P<apt_pk>[0-9]+)/movingout/$', views.set_moving_out_date,
        name='movingout'),

    url(r'^apartments/(?P<apt_pk>[0-9]+)/edit-note/$',
        views.edit_apartment_note, name='edit_apartment_note'),
              
    url(r'^apartments/(?P<apt_pk>[0-9]+)/add-tenant/$',
        views.add_tenant, name='add_tenant'),
    url(r'^tenants/(?P<tenant_id>[0-9]+)/edit/$',
        views.edit_tenant, name='edit_tenant'),
    url(r'^tenants/(?P<tenant_id>[0-9]+)/delete/$',
        views.delete_tenant, name='delete_tenant'),
]

rentcrm/rentcrm/models.py
# -*- coding: utf-8 -*-
import re
import datetime
from calendar import monthrange
from decimal import Decimal
from dateutil import relativedelta
from django.utils import timezone

from django.db import models
from django.db.models import Sum
from django.utils.timezone import now
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.core.validators import MinValueValidator
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse


class Building(models.Model):
    address = models.CharField(max_length=100, unique=True)
    has_garage = models.BooleanField(verbose_name='Garage')

    class Meta:
        ordering = ['address']

    def __str__(self):
        return self.address


class Apartment(models.Model):
    apt_num = models.CharField(max_length=15)
    rent_legal = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    building = models.ForeignKey('Building')
    notes = models.TextField(blank=True)
    # lease = models.OneToOneField('Contract', null=True,
    #         related_name='apartment_active_contract')

    class Meta:
        unique_together = ("apt_num", "building")
        ordering = ['building__address', 'apt_num']

    @property
    def has_active_contract(self):
        return self.contract_set.filter(is_active=True).exists()

    @property
    def current_contract(self):
        try:
            return self.contract_set.get(is_active=True)
        except ObjectDoesNotExist:
            return None

    def __str__(self):
        return '{}, {}'.format(self.apt_num, self.building.address)


class Tenant(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=30)
    email = models.EmailField(blank=True, null=True)
    additional_contacts = models.TextField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def formatted_phone(self, country=None):
        if len(self.phone) >= 10:
            return self.phone[:3] + '-' + self.phone[3:6] + '-' + self.phone[6:]
        else:
            return self.phone

    def save(self, *args, **kwargs):
        self.phone = re.sub(r"\D", "", self.phone)
        super(Tenant, self).save(*args, **kwargs)


class Payment(models.Model):
    date = models.DateField(default=now)
    amount = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    contract = models.ForeignKey('Contract')

    class Meta:
        ordering = ['-date', '-id']

    def __str__(self):
        return '{date} - {amount} from {tenant} for {apartment}'.format(
            amount=self.amount,
            tenant=self.contract.main_tenant_name,
            date=self.date,
            apartment=self.contract.apartment)


class RentAdjustment(models.Model):
    date = models.DateField(default=now)
    amount = models.DecimalField(max_digits=10, decimal_places=2,
        help_text="Enter negative amount to decrease tenant's debt or positive to increase",)
    note = models.CharField(max_length=255, null=True, blank=True)
    contract = models.ForeignKey('Contract')

    class Meta:
        ordering = ['-date', '-id']

    def __str__(self):
        return 'Adjustment for {contract}'.format(contract=self.contract)


class Contract(models.Model):
    ONE_YEAR = 1
    TWO_YEARS = 2
    TERM_CHOICES = ((ONE_YEAR, 'One year'), (TWO_YEARS, 'Two years'))

    lease_start = models.DateField()
    lease_end = models.DateField(null=True, blank=True)
    lease_term = models.IntegerField(choices=TERM_CHOICES, default=ONE_YEAR, verbose_name='Initial lease term')
    signed_date = models.DateField(default=now)
    is_active = models.BooleanField(default=True, verbose_name='Active')
    apartment = models.ForeignKey('Apartment')
    tenants = models.ManyToManyField('Tenant')
    security_deposit = models.DecimalField(max_digits=10, decimal_places=2)

    def get_absolute_url(self):
        return reverse('contract_info', kwargs={'apt_pk': self.apartment.id})

    @property
    def main_tenant_name(self):
        return self.tenants.all().first()

    def contract_end_date(self):
        return self.contractcondition_set.order_by('lease_start').last().lease_end

    def days_till_lease_end(self):
        return (self.contract_end_date() - datetime.datetime.now().date()).days

    @property
    def current_conditions(self):
        cc = self.contractcondition_set.filter(lease_start__lte=timezone.now()).order_by('lease_start').last()
        if not cc:
            cc = self.contractcondition_set.order_by('lease_start').first()
        return cc

    @property
    def is_lease_renewal_offer_sent(self):
        return self.current_conditions.leaserenewaloffer != None

    @property
    def is_lease_renewal_offer_accepted(self):
        return self.current_conditions.leaserenewaloffer.tenant_choice != None

    @property
    def debit(self):
        lease_sum = Decimal('0.00')
        for cc in self.contractcondition_set.all():
            lease_sum += cc.debit

        # Add debt for months after lease end
        today = datetime.datetime.now().date()
        contract_end_date = self.contract_end_date()

        if today > contract_end_date:
            # Lease already ended, but tenant still lives in apartment

            # For the last month of lease we add full monthly rent amount even
            #   if lease ends in the middle of month
            # That's why we start count from 1st day of next month after lease ends

            if contract_end_date.month == 12:
                first_day_after_lease = datetime.date(
                    contract_end_date.year+1, 1, 1)
            else:
                first_day_after_lease = datetime.date(
                    contract_end_date.year, contract_end_date.month+1, 1)

            if today >= first_day_after_lease:
                ddelta = relativedelta.relativedelta(today, first_day_after_lease)
                months_after_lease = ddelta.years * 12 + ddelta.months + 1

                conditions = self.current_conditions
                rent_payment = conditions.rent_preferential + conditions.rent_for_garage

                lease_sum += round(rent_payment * Decimal(months_after_lease), 2)

        adjustments_sum = self.rentadjustment_set.all().aggregate(Sum('amount'))[
            'amount__sum']
        if adjustments_sum:
            lease_sum += adjustments_sum

        return lease_sum

    @property
    def credit(self):
        payments_sum = self.payment_set.all().aggregate(Sum('amount'))[
            'amount__sum']

        return payments_sum if payments_sum else Decimal('0.00')

    @property
    def balance(self):
        return self.credit - self.debit

    def __str__(self):
        return '{building}, {apt} lease with {tenant}'.format(
            apt=self.apartment.apt_num,
            building=self.apartment.building.address,
            tenant=self.main_tenant_name)


class ContractCondition(models.Model):
    # period start date, not lease start! Should be renamed
    lease_start = models.DateField(verbose_name='Period start')
    lease_end = models.DateField(verbose_name='Period end')
    is_active = models.BooleanField()
    rent_preferential = models.DecimalField(max_digits=10, decimal_places=2)
    is_garage_included = models.BooleanField(verbose_name='Garage')
    rent_for_garage = models.DecimalField(
        max_digits=10, decimal_places=2, default=Decimal('0.00'))
    contract = models.ForeignKey('Contract')

    @property
    def days_till_lease_end(self):
        return (self.lease_end - datetime.datetime.now().date()).days

    @property
    def debit(self):
        today = datetime.datetime.now().date()
        period_start_date = self.lease_start

        if today < period_start_date:
            # Lease period (ContractCondition) in future
            return Decimal('0.00')
        else:
            # how much full months
            period_end_date = min(today, self.lease_end)
            ddelta = relativedelta.relativedelta(
                period_end_date,
                datetime.date(period_start_date.year, period_start_date.month, 1)
                )
            month_count = ddelta.years * 12 + ddelta.months  # count from second month

        rent_payment = self.rent_preferential + self.rent_for_garage

        # Calc debt for first month
        if period_start_date.day == 1:
            debit = rent_payment
        else:
            first, days_in_month = monthrange(
                period_start_date.year, period_start_date.month)
            days = days_in_month - period_start_date.day
            debit = round(rent_payment / days_in_month * days, 2)

        return debit + round(rent_payment * Decimal(month_count), 2)

    def __str__(self):
        return 'Period of contract for {building}, apt {apt} from {start} to {end}'.format(
                apt=self.contract.apartment.apt_num,
                building=self.contract.apartment.building.address,
                start=self.lease_start,
                end=self.lease_end
                )

    class Meta:
        verbose_name = 'Lease period'
        verbose_name_plural = 'Lease periods'


class LeaseRenewalOffer(models.Model):
    # ONE_YR = 1
    # TWO_YRS = 2
    # STOP_LEASE = 0
    # TERM_CHOICES = ((ONE_YR, 'One year term'), (TWO_YRS, 'Two years term'))
    ACCEPTANCE_CHOICES = ((1, 'One year term'),
                          (2, 'Two years term'), (0, 'No renew'))
    # YES = True
    # NO = False
    # ACCEPTANCE_CHOICES = ((YES, 'Offer accepted'), (NO, 'Offer rejected'))
    # new_term = models.IntegerField(choices=TERM_CHOICES)
    tenant_choice = models.SmallIntegerField(
        choices=ACCEPTANCE_CHOICES, blank=True, null=True)
    date_issued = models.DateField(default=now)

rentcrm/rentcrm/forms.py
from django import forms
from .models import Apartment, Payment, RentAdjustment, Contract, Tenant, ContractCondition, LeaseRenewalOffer


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ('date', 'amount',)
        widgets = {
            'date': forms.DateInput(attrs={'class': 'datepicker'}),
            'amount': forms.NumberInput(attrs={'autofocus': ''})
        }


class RentAdjustmentForm(forms.ModelForm):
    class Meta:
        model = RentAdjustment
        fields = ('date', 'amount', 'note')
        widgets = {'date': forms.DateInput(attrs={'class': 'datepicker'}),
                    'note': forms.TextInput(attrs={'size': '40'})
                    }


class TenantForm(forms.ModelForm):
    class Meta:
        model = Tenant
        fields = '__all__'
        widgets = {
            'additional_contacts': forms.Textarea(attrs={'cols': 80, 'rows': 3}),
            'notes': forms.Textarea(attrs={'cols': 80, 'rows': 5}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class ApartmentNotesForm(forms.ModelForm):
    class Meta:
        model = Apartment
        fields = ['notes']


class LegalRentForm(forms.ModelForm):
    class Meta:
        model = Apartment
        fields = ['rent_legal']
        widgets = {'rent_legal': forms.NumberInput(attrs={'class': 'form-control'})}


class ContractForm(forms.ModelForm):
    class Meta:
        model = Contract
        fields = ('lease_term',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['lease_term'].widget.attrs.update({
            'class': 'form-control'
        })


class MovingOutForm(forms.ModelForm):
    class Meta:
        model = Contract
        fields = ('lease_end',)
        widgets = {'lease_end': forms.DateInput(attrs={'class': 'datepicker'})}
        labels = {'lease_end': 'Moving Out date'}


class ContractConditionForm(forms.ModelForm):
    class Meta:
        model = ContractCondition
        fields = ('lease_start',
                  'is_garage_included', 'rent_for_garage',)
        widgets = {'lease_start': forms.DateInput(
            attrs={'class': 'datepicker form-control', ' autocomplete': 'off'})}


class LeaseRenewalOfferForm(forms.ModelForm):
    class Meta:
        model = LeaseRenewalOffer
        fields = ('date_issued', 'rent_legal_one_year', 'rent_preferential_one_year',
                  'rent_legal_two_years', 'rent_preferential_two_years',
                  'is_garage_included', 'rent_for_garage')
        widgets = {'date_issued': forms.DateInput(
            attrs={'class': 'datepicker'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            if not (field in {'is_garage_included', 'date_issued'}):
                self.fields[field].widget.attrs.update({
                    'class': 'form-control'
                })


class GarageForm(forms.ModelForm):
    class Meta:
        model = ContractCondition
        fields = ('is_garage_included', 'rent_for_garage')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['rent_for_garage'].widget.attrs.update({
            'class': 'form-control'
        })


class TermForm(forms.ModelForm):
    class Meta:
        model = LeaseRenewalOffer
        fields = ('tenant_choice', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tenant_choice'].widget.attrs.update({
            'class': 'form-control'
        })


class OfferAcceptanceForm(forms.ModelForm):
    class Meta:
        model = LeaseRenewalOffer
        fields = ('tenant_choice', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tenant_choice'].widget.attrs.update({
            'class': 'form-control'
        })

rentcrm/rentcrm/templates/rentcrm/details/cc-info.html
{% extends '../base.html' %}
{% load static %}{% load humanize %}

{% block title %}{{ apartment }}{% endblock %}

{% block content %}

	<div class="container">
	  <ol class="breadcrumb">
	    <li><a href="/">All Buildings</a></li>
	    <li><a href="{% url 'building_apartments' apartment.building.pk %}">{{ apartment.building }}</a></li>
	    <li class="active">{{ apartment.apt_num }}</li>
	  </ol>
	</div>

	<div class="container-fluid">
	  <h1>Lease details for {{ apartment }} </h1>
	  <div class="row">

	  	{% if apartment.has_active_contract %}
			{% with contract=apartment.current_contract %}
			{% with tenants=contract.tenants.all %}
			{% with conditions=contract.current_conditions %}
	    <div class="col-sm-3">
	    	<h2>Lease detail</h2>
	    	<p><strong>Legal Rent: </strong>${{ apartment.rent_legal|intcomma }}</p>
	    	<p><strong>Preferential Rent: </strong>${{ conditions.rent_preferential|intcomma }}</p>
	    	<p><strong>Additional payments:<br>Garage :
	    		</strong>
	    		{% if conditions.is_garage_included %}
	    			${{conditions.rent_for_garage}}
	    		{% else %}
	    			No
	    		{% endif %}
	    	</p>
	    	<p><strong>Lease period start: </strong>{{ conditions.lease_start }}</p>
	    	<p><strong>Lease period end: </strong>{{ conditions.lease_end }}</p>
				<p><strong>Balance: </strong>{{ contract.balance|intcomma }}</p>
				<p><strong>Security deposit: </strong>${{ contract.security_deposit|intcomma }}</p>

				<h3>Apartment notes</h3>
				<form action="{% url 'edit_apartment_note' apartment.id %}?next={{ request.get_full_path|urlencode }}" method="post">{% csrf_token %}
						<textarea id="id_notes" class="form-control" name="notes" rows="3">{{ apartment.notes }}</textarea>
						<button class="btn btn-success" type="submit" name="button">Save</button>

				</form>

	    </div>

			<div class="col-sm-3">
	    	<h2>Tenant{{tenants|pluralize}}</h2>
	    	{% for tenant in tenants %}
	    		<h3>{{ tenant.name }}</h3>
					<p><strong>Phone: </strong>{{ tenant.formatted_phone }}</p>
					{% if tenant.email %}
					<p><strong>Email: </strong>{{ tenant.email }}</p>
					{% endif %}
					{% if tenant.additional_contacts %}
					<p><strong>Additional contacts: </strong></p>
					<p>{{ tenant.additional_contacts }}</p>
					{% endif %}
					{% if tenant.notes %}
					<p><strong>Notes: </strong></p>
					<p>{{ tenant.notes|linebreaks }}</p>
					{% endif %}
					<a href="{% url 'edit_tenant' tenant.id %}?next={{ request.get_full_path|urlencode }}" title="Edit tenant"><span class="glyphicon glyphicon-pencil"></span></a>
					<hr>
	    	{% endfor %}
	    </div>

	    <div class="col-sm-3">
	    	<h2>Payments</h2>
				{% with payments=contract.payment_set.all %}
				{% if payments %}
	    	<ul>
	    		{% for payment in payments|slice:":5" %}
	    			<li><strong>{{ payment.date }}</strong>: ${{ payment.amount|intcomma }}</li>
	    		{% endfor %}
					{% if payments|length > 5 %}
						<a href="{% url 'contract_payments' contract.id %}">View all payments</a>
					{% endif %}
	    	</ul>
				{% else %}
					<p>No payments yet!</p>
				{% endif %}
				{% endwith %}
				<h2>Adjustments</h2>
				<ul>
	    		{% for adjustment in contract.rentadjustment_set.all %}
	    			<li>
							<strong>{{ adjustment.date }}</strong>: {{ adjustment.amount|intcomma }}
							<br>
							<span>{{ adjustment.note }}</span>
						</li>
					{% empty %}
						<p>No adjustments yet!</p>
					{% endfor %}
	    	</ul>
	    </div>

	    <div class="col-sm-3">
	    	<h2>Actions</h2>
	    	<p><a href="{% url 'add_payment' apartment.id %}?next={{ request.get_full_path|urlencode }}" class="btn btn-xs btn-success">Add Payment</a></p>
	    	<p><a href="{% url 'rent_adjustment' apartment.id %}?next={{ request.get_full_path|urlencode }}" class="btn btn-xs btn-success">Rent Adjustment</a></p>

				{% if contract.lease_end %}
				<p>Moving out date is {{ contract.lease_end }}</p>
				{% endif %}
				<p><a href="{% url 'movingout' apartment.id %}?prev={{ request.get_full_path|urlencode }}" class="btn btn-xs btn-warning">Set Moving Out date</a></p>

				<p><a href="{% url 'end_lease' apartment.id %}?prev={{ request.get_full_path|urlencode }}" class="btn btn-xs btn-danger">Moved Out</a></p>

        {% if conditions.days_till_lease_end <= 100 %}
        	{% if contract.is_lease_renewal_offer_sent %}
        		<p>Lease renewal offer form was sent {{ conditions.leaserenewaloffer.date_issued }}</p>
        		{% if not conditions.leaserenewaloffer.is_accepted %}
							<p><a href="{% url 'update_lease' apartment.id %}" class="btn btn-xs btn-info">Update lease</a></p>
						{% else %}
							<p>Tenant chose {{ conditions.leaserenewaloffer.get_tenant_choice_display }}</p>
						{% endif %}
	        {% else %}
						<p><a href="{% url 'send-renewal' apartment.id %}" class="btn btn-xs btn-info">Send renewal</a></p>
					{% endif %}
	      {% endif %}

				<p><a href="{% url 'add_tenant' apartment.id %}?next={{ request.get_full_path|urlencode }}" class="btn btn-xs btn-primary">Add tenant</a></p>

				<p><a href="{% url 'admin:rentcrm_contract_change' contract.id %}" class="btn btn-xs btn-default">Edit contract details</a></p>

				{% endwith %}
				{% endwith %}
				{% endwith %}

	    {% else %}
    	<div class="container-fluid">
		    <p>The apartments are not occupied currently</p>
			</div>
		{% endif %}
	    </div>
	  </div>
	</div>
{% endblock %}

rentcrm/rentcrm/templates/rentcrm/details/contract-payments.html
{% extends '../base.html' %}
{% load static %}{% load humanize %}

{% block title %}{{ contract }}{% endblock %}

{% block content %}

	<div class="container">
		<ol class="breadcrumb">
			<li><a href="{% url 'contract_info' contract.apartment.id %}">{{ contract }}</a></li>
			<li class="active">Payments search</li>
		</ol>
	</div>

	<div class="container-fluid">
	  <h1>Payments for {{ contract }}</h1>
	  <div class="row">
			{% with tenants=contract.tenants.all %}
			{% with conditions=contract.current_conditions %}
	    <div class="col-sm-3">
				<h2>Search</h2>
				<form method="get">
					<label for="from">From:</label><br>
					<input class="form-control datepicker" type="date" name="from" value="{{ request.GET.from }}">
					<br>
					<label for="to">To:</label><br>
					<input class="form-control datepicker" type="date" name="to" value="{{ request.GET.to }}">
					<br>
					<input type="submit" value="Show payments">
				</form>
	    </div>

	    <div class="col-sm-3">
	    	<h2>Payments</h2>
	    	<ul>
	    		{% for payment in payments %}
	    			<li><strong>{{ payment.date }}</strong>: ${{ payment.amount|intcomma }}</li>
					{% empty %}
						<p>No payments yet!</p>
					{% endfor %}
				</ul>
	    </div>

			<div class="col-sm-3">
				<h2>Adjustments</h2>
				<ul>
	    		{% for adjustment in adjustments %}
	    			<li>
							<strong>{{ adjustment.date }}</strong>: {{ adjustment.amount|intcomma }}
							<br>
							<span>{{ adjustment.note }}</span>
						</li>
					{% empty %}
						<p>No adjustments yet!</p>
					{% endfor %}
	    	</ul>
			</div>

			<div class="col-sm-3">
				<h2>Lease detail</h2>
				<p><strong>Legal Rent: </strong>${{ contract.apartment.rent_legal|intcomma }}</p>
				<p><strong>Preferential Rent: </strong>${{ conditions.rent_preferential|intcomma }}</p>
				<p><strong>Additional payments:<br>Garage :
					</strong>
					{% if conditions.is_garage_included %}
						${{conditions.rent_for_garage}}
					{% else %}
						No
					{% endif %}
				</p>
				<p><strong>Lease period start: </strong>{{ conditions.lease_start }}</p>
				<p><strong>Lease period end: </strong>{{ conditions.lease_end }}</p>
				<p><strong>Balance: </strong>{{ contract.balance|intcomma }}</p>
				<p><strong>Security deposit: </strong>${{ contract.security_deposit|intcomma }}</p>

	    	<h2>Tenant{{tenants|pluralize}}</h2>
	    	{% for tenant in tenants %}
	    		<h3>{{ tenant.name }}</h3>
					<p><strong>Phone: </strong>{{ tenant.formatted_phone }}</p>
					{% if tenant.email %}
					<p><strong>Email: </strong>{{ tenant.email }}</p>
					{% endif %}
					{% if tenant.additional_contacts %}
					<p><strong>Additional contacts: </strong></p>
					<p>{{ tenant.additional_contacts }}</p>
					{% endif %}
					{% if tenant.notes %}
					<p><strong>Notes: </strong></p>
					<p>{{ tenant.notes }}</p>
					{% endif %}
					<a href="{% url 'edit_tenant' tenant.id %}?next={{ request.get_full_path|urlencode }}" title="Edit tenant"><span class="glyphicon glyphicon-pencil"></span></a>
					<hr>
	    	{% endfor %}
	    </div>

			{% endwith %}
			{% endwith %}

	  </div>
	</div>
{% endblock %}