rentcrm/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rentcrm import views

admin.site.site_header = 'RentCRM administration'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^scripts/', include('scripts.urls')),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^', include('rentcrm.urls'))
]

rentcrm/rentcrm/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='apartments_all'),
    url(r'^free/$', views.free, name='apartments_free'),
    url(r'^moving-out/$', views.moving_out, name='apartments_moving_out'),
    url(r'^debitors/$', views.debitors, name='apartments_debt'),
    url(r'^renewal-required/$', views.renewal_required, name='apartments_renew'),
    url(r'^renewal-sent/$', views.renewal_sent, name='apartments_update'),
    url(r'^renewal-send-pastdue/$', views.renewal_send_pastdue, name='renewal_send_pastdue'),
    url(r'^renewal-pastdue/$', views.renewal_pastdue, name='renewal_pastdue'),

    url(r'^building/(?P<building_pk>[0-9]+)/$',
        views.building_apartments, name='building_apartments'),

    url(r'^apartments/(?P<apt_pk>[0-9]+)/$',
        views.cc_info, name='contract_info'),
    url(r'^contracts/(?P<contract_id>[0-9]+)/payments/$',
        views.contract_payments, name='contract_payments'),

    url(r'^apartments/(?P<apt_pk>[0-9]+)/send-renewal/$',
        views.send_renewal, name='send-renewal'),
    url(r'^apartments/(?P<apt_pk>[0-9]+)/update-lease/$',
        views.update_lease, name='update_lease'),
    url(r'^apartments/(?P<apt_pk>[0-9]+)/pay-in/$', views.pay_in, name='add_payment'),
    url(r'^apartments/(?P<apt_pk>[0-9]+)/adjust/$', views.rent_adjustment, name='rent_adjustment'),
    url(r'^apartments/(?P<apt_pk>[0-9]+)/start-lease/$',
        views.start_lease, name='start_lease'),
    url(r'^apartments/(?P<apt_pk>[0-9]+)/end-lease/$',
        views.end_lease, name='end_lease'),
    url(r'^apartments/(?P<apt_pk>[0-9]+)/movingout/$', views.set_moving_out_date,
        name='movingout'),

    url(r'^apartments/(?P<apt_pk>[0-9]+)/edit-note/$',
        views.edit_apartment_note, name='edit_apartment_note'),
              
    url(r'^apartments/(?P<apt_pk>[0-9]+)/add-tenant/$',
        views.add_tenant, name='add_tenant'),
    url(r'^tenants/(?P<tenant_id>[0-9]+)/edit/$',
        views.edit_tenant, name='edit_tenant'),
    url(r'^tenants/(?P<tenant_id>[0-9]+)/delete/$',
        views.delete_tenant, name='delete_tenant'),
]

rentcrm/rentcrm/models.py
# -*- coding: utf-8 -*-
import re
import datetime
from calendar import monthrange
from decimal import Decimal
from dateutil import relativedelta
from django.utils import timezone

from django.db import models
from django.db.models import Sum
from django.utils.timezone import now
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.core.validators import MinValueValidator
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse


class Building(models.Model):
    address = models.CharField(max_length=100, unique=True)
    has_garage = models.BooleanField(verbose_name='Garage')

    class Meta:
        ordering = ['address']

    def __str__(self):
        return self.address


class Apartment(models.Model):
    apt_num = models.CharField(max_length=15)
    rent_legal = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    building = models.ForeignKey('Building')
    notes = models.TextField(blank=True)
    # lease = models.OneToOneField('Contract', null=True,
    #         related_name='apartment_active_contract')

    class Meta:
        unique_together = ("apt_num", "building")
        ordering = ['building__address', 'apt_num']

    @property
    def has_active_contract(self):
        return self.contract_set.filter(is_active=True).exists()

    @property
    def current_contract(self):
        try:
            return self.contract_set.get(is_active=True)
        except ObjectDoesNotExist:
            return None

    def __str__(self):
        return '{}, {}'.format(self.apt_num, self.building.address)


class Tenant(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=30)
    email = models.EmailField(blank=True, null=True)
    additional_contacts = models.TextField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def formatted_phone(self, country=None):
        if len(self.phone) >= 10:
            return self.phone[:3] + '-' + self.phone[3:6] + '-' + self.phone[6:]
        else:
            return self.phone

    def save(self, *args, **kwargs):
        self.phone = re.sub(r"\D", "", self.phone)
        super(Tenant, self).save(*args, **kwargs)


class Payment(models.Model):
    date = models.DateField(default=now)
    amount = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    contract = models.ForeignKey('Contract')

    class Meta:
        ordering = ['-date', '-id']

    def __str__(self):
        return '{date} - {amount} from {tenant} for {apartment}'.format(
            amount=self.amount,
            tenant=self.contract.main_tenant_name,
            date=self.date,
            apartment=self.contract.apartment)


class RentAdjustment(models.Model):
    date = models.DateField(default=now)
    amount = models.DecimalField(max_digits=10, decimal_places=2,
        help_text="Enter negative amount to decrease tenant's debt or positive to increase",)
    note = models.CharField(max_length=255, null=True, blank=True)
    contract = models.ForeignKey('Contract')

    class Meta:
        ordering = ['-date', '-id']

    def __str__(self):
        return 'Adjustment for {contract}'.format(contract=self.contract)


class Contract(models.Model):
    ONE_YEAR = 1
    TWO_YEARS = 2
    TERM_CHOICES = ((ONE_YEAR, 'One year'), (TWO_YEARS, 'Two years'))

    lease_start = models.DateField()
    lease_end = models.DateField(null=True, blank=True)
    lease_term = models.IntegerField(choices=TERM_CHOICES, default=ONE_YEAR, verbose_name='Initial lease term')
    signed_date = models.DateField(default=now)
    is_active = models.BooleanField(default=True, verbose_name='Active')
    apartment = models.ForeignKey('Apartment')
    tenants = models.ManyToManyField('Tenant')
    security_deposit = models.DecimalField(max_digits=10, decimal_places=2)

    def get_absolute_url(self):
        return reverse('contract_info', kwargs={'apt_pk': self.apartment.id})

    @property
    def main_tenant_name(self):
        return self.tenants.all().first()

    def contract_end_date(self):
        return self.contractcondition_set.order_by('lease_start').last().lease_end

    def days_till_lease_end(self):
        return (self.contract_end_date() - datetime.datetime.now().date()).days

    @property
    def current_conditions(self):
        cc = self.contractcondition_set.filter(lease_start__lte=timezone.now()).order_by('lease_start').last()
        if not cc:
            cc = self.contractcondition_set.order_by('lease_start').first()
        return cc

    @property
    def is_lease_renewal_offer_sent(self):
        return self.current_conditions.leaserenewaloffer != None

    @property
    def is_lease_renewal_offer_accepted(self):
        return self.current_conditions.leaserenewaloffer.tenant_choice != None

    @property
    def debit(self):
        lease_sum = Decimal('0.00')
        for cc in self.contractcondition_set.all():
            lease_sum += cc.debit

        # Add debt for months after lease end
        today = datetime.datetime.now().date()
        contract_end_date = self.contract_end_date()

        if today > contract_end_date:
            # Lease already ended, but tenant still lives in apartment

            # For the last month of lease we add full monthly rent amount even
            #   if lease ends in the middle of month
            # That's why we start count from 1st day of next month after lease ends

            if contract_end_date.month == 12:
                first_day_after_lease = datetime.date(
                    contract_end_date.year+1, 1, 1)
            else:
                first_day_after_lease = datetime.date(
                    contract_end_date.year, contract_end_date.month+1, 1)

            if today >= first_day_after_lease:
                ddelta = relativedelta.relativedelta(today, first_day_after_lease)
                months_after_lease = ddelta.years * 12 + ddelta.months + 1

                conditions = self.current_conditions
                rent_payment = conditions.rent_preferential + conditions.rent_for_garage

                lease_sum += round(rent_payment * Decimal(months_after_lease), 2)

        adjustments_sum = self.rentadjustment_set.all().aggregate(Sum('amount'))[
            'amount__sum']
        if adjustments_sum:
            lease_sum += adjustments_sum

        return lease_sum

    @property
    def credit(self):
        payments_sum = self.payment_set.all().aggregate(Sum('amount'))[
            'amount__sum']

        return payments_sum if payments_sum else Decimal('0.00')

    @property
    def balance(self):
        return self.credit - self.debit

    def __str__(self):
        return '{building}, {apt} lease with {tenant}'.format(
            apt=self.apartment.apt_num,
            building=self.apartment.building.address,
            tenant=self.main_tenant_name)


class ContractCondition(models.Model):
    # period start date, not lease start! Should be renamed
    lease_start = models.DateField(verbose_name='Period start')
    lease_end = models.DateField(verbose_name='Period end')
    is_active = models.BooleanField()
    rent_preferential = models.DecimalField(max_digits=10, decimal_places=2)
    is_garage_included = models.BooleanField(verbose_name='Garage')
    rent_for_garage = models.DecimalField(
        max_digits=10, decimal_places=2, default=Decimal('0.00'))
    contract = models.ForeignKey('Contract')

    @property
    def days_till_lease_end(self):
        return (self.lease_end - datetime.datetime.now().date()).days

    @property
    def debit(self):
        today = datetime.datetime.now().date()
        period_start_date = self.lease_start

        if today < period_start_date:
            # Lease period (ContractCondition) in future
            return Decimal('0.00')
        else:
            # how much full months
            period_end_date = min(today, self.lease_end)
            ddelta = relativedelta.relativedelta(
                period_end_date,
                datetime.date(period_start_date.year, period_start_date.month, 1)
                )
            month_count = ddelta.years * 12 + ddelta.months  # count from second month

        rent_payment = self.rent_preferential + self.rent_for_garage

        # Calc debt for first month
        if period_start_date.day == 1:
            debit = rent_payment
        else:
            first, days_in_month = monthrange(
                period_start_date.year, period_start_date.month)
            days = days_in_month - period_start_date.day
            debit = round(rent_payment / days_in_month * days, 2)

        return debit + round(rent_payment * Decimal(month_count), 2)

    def __str__(self):
        return 'Period of contract for {building}, apt {apt} from {start} to {end}'.format(
                apt=self.contract.apartment.apt_num,
                building=self.contract.apartment.building.address,
                start=self.lease_start,
                end=self.lease_end
                )

    class Meta:
        verbose_name = 'Lease period'
        verbose_name_plural = 'Lease periods'


class LeaseRenewalOffer(models.Model):
    # ONE_YR = 1
    # TWO_YRS = 2
    # STOP_LEASE = 0
    # TERM_CHOICES = ((ONE_YR, 'One year term'), (TWO_YRS, 'Two years term'))
    ACCEPTANCE_CHOICES = ((1, 'One year term'),
                          (2, 'Two years term'), (0, 'No renew'))
    # YES = True
    # NO = False
    # ACCEPTANCE_CHOICES = ((YES, 'Offer accepted'), (NO, 'Offer rejected'))
    # new_term = models.IntegerField(choices=TERM_CHOICES)
    tenant_choice = models.SmallIntegerField(
        choices=ACCEPTANCE_CHOICES, blank=True, null=True)
    date_issued = models.DateField(default=now)

rentcrm/rentcrm/forms.py
from django import forms
from .models import Apartment, Payment, RentAdjustment, Contract, Tenant, ContractCondition, LeaseRenewalOffer


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ('date', 'amount',)
        widgets = {
            'date': forms.DateInput(attrs={'class': 'datepicker'}),
            'amount': forms.NumberInput(attrs={'autofocus': ''})
        }


class RentAdjustmentForm(forms.ModelForm):
    class Meta:
        model = RentAdjustment
        fields = ('date', 'amount', 'note')
        widgets = {'date': forms.DateInput(attrs={'class': 'datepicker'}),
                    'note': forms.TextInput(attrs={'size': '40'})
                    }


class TenantForm(forms.ModelForm):
    class Meta:
        model = Tenant
        fields = '__all__'
        widgets = {
            'additional_contacts': forms.Textarea(attrs={'cols': 80, 'rows': 3}),
            'notes': forms.Textarea(attrs={'cols': 80, 'rows': 5}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class ApartmentNotesForm(forms.ModelForm):
    class Meta:
        model = Apartment
        fields = ['notes']


class LegalRentForm(forms.ModelForm):
    class Meta:
        model = Apartment
        fields = ['rent_legal']
        widgets = {'rent_legal': forms.NumberInput(attrs={'class': 'form-control'})}


class ContractForm(forms.ModelForm):
    class Meta:
        model = Contract
        fields = ('lease_term',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['lease_term'].widget.attrs.update({
            'class': 'form-control'
        })


class MovingOutForm(forms.ModelForm):
    class Meta:
        model = Contract
        fields = ('lease_end',)
        widgets = {'lease_end': forms.DateInput(attrs={'class': 'datepicker'})}
        labels = {'lease_end': 'Moving Out date'}


class ContractConditionForm(forms.ModelForm):
    class Meta:
        model = ContractCondition
        fields = ('lease_start',
                  'is_garage_included', 'rent_for_garage',)
        widgets = {'lease_start': forms.DateInput(
            attrs={'class': 'datepicker form-control', ' autocomplete': 'off'})}


class LeaseRenewalOfferForm(forms.ModelForm):
    class Meta:
        model = LeaseRenewalOffer
        fields = ('date_issued', 'rent_legal_one_year', 'rent_preferential_one_year',
                  'rent_legal_two_years', 'rent_preferential_two_years',
                  'is_garage_included', 'rent_for_garage')
        widgets = {'date_issued': forms.DateInput(
            attrs={'class': 'datepicker'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            if not (field in {'is_garage_included', 'date_issued'}):
                self.fields[field].widget.attrs.update({
                    'class': 'form-control'
                })


class GarageForm(forms.ModelForm):
    class Meta:
        model = ContractCondition
        fields = ('is_garage_included', 'rent_for_garage')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['rent_for_garage'].widget.attrs.update({
            'class': 'form-control'
        })


class TermForm(forms.ModelForm):
    class Meta:
        model = LeaseRenewalOffer
        fields = ('tenant_choice', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tenant_choice'].widget.attrs.update({
            'class': 'form-control'
        })


class OfferAcceptanceForm(forms.ModelForm):
    class Meta:
        model = LeaseRenewalOffer
        fields = ('tenant_choice', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tenant_choice'].widget.attrs.update({
            'class': 'form-control'
        })

rentcrm/rentcrm/templates/rentcrm/adjust.html
{% extends './base.html' %}
{% block title %}Rent adjustment for {{ apartment }}{% endblock %}

{% block content %}
	<h1>Rent adjustment for apartment {{ apartment.apt_num }},
	{{ apartment.building.address }}</h1>
	{% if apartment.has_active_contract %}
	<form method="POST" >
		{% csrf_token %}
		{{ form.as_p }}
		<div class="rent-adj-submit">
			<button type="submit" class="btn btn-xs btn-success">Submit adjustment</button>
		</div>
	</form>
	<p>
		Negative amount decrease tenant debt, positive - increase. Current balance is {{ apartment.current_contract.balance }}
	</p>
	{% else %}
	<p>The apartments are not occupied currently</p>
	{% endif %}
{% endblock %}

rentcrm/rentcrm/templates/rentcrm/apartments-table.html
{% load humanize %}<table class="table table-hover table-responsive" id="apartments_table">
  <thead>
    <tr>
      <th>Building</th>
      <th>Apt</th>
      <th>Lease Term</th>
      <th>Tenant</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Rent Legal</th>
      <th>Rent Preferential</th>
      <th>Garage</th>
      <th>Balance</th>
    </tr>
  </thead>
  <tbody>
    {% for apartment in apartments %}
      {% with contract=apartment.current_contract %}
      {% if contract %}
      {% with balance=contract.balance %}
      {% with tenants=contract.tenants.all %}
      {% with current_conditions=contract.current_conditions %}
      {% with days_till_lease_end=contract.days_till_lease_end %}
      <tr class="{% if days_till_lease_end < 30 or days_till_lease_end <= 100 and not contract.is_lease_renewal_offer_sent %}
                    danger
                  {% elif days_till_lease_end < 30 %}
                    danger
                  {% elif balance < 0 %}
                    warning
                  {% comment %}
                  {% elif days_till_lease_end <= 120 and not contract.is_lease_renewal_offer_accepted %}
                    info
                  {% else %}
                    success
                  {% endcomment %}
                  {% endif %}">
        <td>{{ apartment.building }}</td>
        <td>{{ apartment.apt_num }}</td>
        <td>
            <a href="{% url 'contract_info' apartment.id %}">
              {{ current_conditions.lease_start }}
              <br />
              {{ current_conditions.lease_end }}
            </a>
            {% if contract.lease_end %}
            <br>
            <a href="{% url 'movingout' apartment.id %}?prev={{ request.get_full_path|urlencode }}" class="label label-danger">Moving out: {{ contract.lease_end }}</a>
            {% endif %}
            {% if current_conditions.days_till_lease_end <= 120 %}
              {% if contract.is_lease_renewal_offer_sent %}
                {% if not current_conditions.leaserenewaloffer.is_accepted %}
                <br /><a href="{% url 'update_lease' apartment.id %}?next={{ request.get_full_path|urlencode }}" class="btn btn-xs btn-info">Update lease</a>
                {% endif %}
              {% else %}
                <br /><a href="{% url 'send-renewal' apartment.id %}?next={{ request.get_full_path|urlencode }}" class="btn btn-xs btn-info">Send renewal</a>
              {% endif %}
            {% endif %}
        </td>

        <td>{% for tenant in tenants %}
              {{ tenant.name }} <br>
            {% endfor %}
        </td>

        <td>{% for tenant in tenants %}
              <span>{{ tenant.formatted_phone }}</span><br>
            {% endfor %}
        </td>

        <td>{% for tenant in tenants %}
              {{ tenant.email }} <br>
            {% endfor %}
        </td>

        <td>${{ apartment.rent_legal|intcomma }}</td>

        <td>${{ current_conditions.rent_preferential|intcomma }}</td>

        <td>{% if current_conditions.is_garage_included %}
          ${{ current_conditions.rent_for_garage|intcomma }}
          {% else %}
          No
          {% endif %}
        </td>

        <td>
          {{ balance|intcomma }}
          <br /><a href="{% url 'add_payment' apartment.id %}?next={{ request.get_full_path|urlencode }}" class="btn btn-xs btn-success">Add Payment</a>
        </td>
      </tr>
      {% endwith %}
      {% endwith %}
      {% endwith %}
      {% endwith %}
      {% else %}
      <tr>
        <td>{{ apartment.building }}</td>
        <td>{{ apartment.apt_num }}</td>
        <td>
          <a href="{% url 'start_lease' apartment.id %}" class="btn btn-xs btn-primary">Start lease</a>
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td>${{ apartment.rent_legal|intcomma }}</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      {% endif %}
      {% endwith %}
    {% endfor %}
  </tbody>
</table>

rentcrm/rentcrm/templates/rentcrm/debitors.html
{% extends './base.html' %}
{% load static %}

{% block title %}Debitors{% endblock %}

{% block menu-debtors-active %} class="active"{% endblock %}

rentcrm/rentcrm/templates/rentcrm/free.html
{% extends './base.html' %}
{% load static %}

{% block title %} Free Apartments {% endblock %}

{% block menu-free-active %} class="active"{% endblock %}

rentcrm/rentcrm/templates/rentcrm/index.html
{% extends './base.html' %}
{% load static %}

{% block title %}All Apartments{% endblock %}

{% block menu-all-active %} class="active"{% endblock %}

rentcrm/rentcrm/templates/rentcrm/send_renewal.html
{% extends './base.html' %}
{% load static %}

{% block title %}Send renewal{% endblock %}

{% block scripts %}

	$('#rent_garage_div').hide();

	$('#id_rent_for_garage').hide();
	$('label[for="id_rent_for_garage"]').hide();
	$('#offer_sent_message').delay(1000).fadeOut('fast');

	$('#id_is_garage_included').click(function(){
		$('#id_rent_for_garage').val('0.0');
		$('#id_rent_for_garage').toggle();
		$('label[for="id_rent_for_garage"]').toggle();
	});

	$('#submit_button').click(function(){
		$('#offer_sent_message').show();
		$('#offer_sent_message').delay(1000).fadeOut('fast');
	});

{% endblock %}
{% block content %}
	<h1>Lease Renewal Form for {{ apartment }}</h1>

	<div class="row">
		<div class="col-md-6">
			<form method='POST' style="width:50%">
				{% csrf_token %}
				{{ offerform.as_p }}

				<p><button type="submit" class="btn btn-xl btn-success" id="submit_button">Send</button><a href="/" class="btn btn-xl btn-warning" style="margin-left:1em">Cancel</a></p>

				{% if offer_sent_already %}
					<p id="offer_sent_message" style="color:#A65043"><strong>Renewal offer form was sent already</strong></p>
				{% endif %}
			</form>
		</div>
		<div class="col-md-6">
			<h2>Current conditions</h2>
			<strong>Rent legal</strong>: {{ apartment.rent_legal }}
			<strong>Rent preferential</strong>: {{ apartment.current_contract.current_conditions.rent_preferential }}
			<h3>Tenant{{ apartment.current_contract.tenants.all|pluralize }}</h3>
			<ul>
				{% for tenant in apartment.current_contract.tenants.all %}
					<li>{{ tenant.name }}</li>
				{% endfor %}
			</ul>
		</div>
	</div>
{% endblock %}

rentcrm/rentcrm/templates/rentcrm/tenant-add.html
{% extends './base.html' %}
{% load static %}

{% block title %}{{ apartment }} new lease{% endblock %}

{% block scripts %}
$(function(){
	$( "#formsubmit" ).click(function() {
		$( "form" ).submit(function(evt){


			name = $( '#id_name' ).val();
			phone = $( '#id_phone' ).val();

			if((name === '') && (phone === '')){
				alert("You must enter tenant's name and phone at least");
				evt.preventDefault();
			} else {
			    $( '#myModal' ).modal('show');
			}



		});
	});
});
{% endblock %}

{% block content %}
<h1>Additional tenant for apartment {{ apartment.apt_num }}, {{ apartment.building.address }}</h1>

{% if apartment.has_active_contract %}
<form method="POST" style="width:50%">
	{% csrf_token %}
	<div class="row">
		<div class="col-md-6">
			<h2>Tenant details</h2>
			{{ tenantform.as_p }}
			<p><button type="submit" class="btn btn-xl btn-success" data-toggle="modal" data-target="#myModal" id="formsubmit">Add tenant</button></p>
		</div>
	</div>
</form>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
	<div class="modal-dialog modal-sm">

		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Tenant was successfully added</h4>
			</div>
			<div class="modal-body">
				<p>Add another?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Yes</button>
				<a href="{% url 'apartments_all' %}" class="btn btn-primary">No</a>
			</div>
		</div>
	</div>
</div>
{% else %}
<p>The apartments are not occupied currently</p>
{% endif %}
{% endblock %}

rentcrm/rentcrm/templates/rentcrm/update-lease.html
{% extends './base.html' %}
{% load static %}
{% block title %}Enter tenant choice for {{ apartment }}{% endblock %}
{% block scripts %}
$(function(){

	$('#id_rent_for_garage').hide();
	$('label[for="id_rent_for_garage"]').hide();
	$('#rent_sum').hide();
	$('#accepted_inputs').hide();
	$('#updated_already_message').delay(1000).fadeOut('fast');

	$('#id_is_garage_included').click(function(){
		$('#id_rent_for_garage').val('');
		$('#id_rent_for_garage').toggle();
		$('label[for="id_rent_for_garage"]').toggle();
	});

	$('#id_new_term').change(function(){
     	$('#rent_sum').show();
		$('.appended').remove();
		if ($('option:selected', this).attr('value') == 1){
			$('#rent_sum').append('<span class="appended">{{ sent_offer.rent_preferential_one_year }}</span>');
		} else {
			if ($('option:selected', this).attr('value') == 2){
				$('#rent_sum').append('<span class="appended">{{ sent_offer.rent_preferential_two_years }}</span>');
			} else {
				if ($('option:selected', this).attr('value') == ''){
					$('#rent_sum').hide();
				}
			}
		}
	});

	$('#submit_button').click(function(){
		$('#updated_already_message').show();
		$('#updated_already_message').delay(1000).fadeOut('fast');
	});

	$('#id_is_accepted').change(function(){
		if ($('option:selected', this).attr('value') == "True"){
			$('#accepted_inputs').show();
		} else {
			$('#accepted_inputs').hide();
		};
		if ('{{ updated_already }}'){
			$('#updated_already_message').show();
			$('#updated_already_message').delay(1000).fadeOut('fast');
		}
	});
});
{% endblock %}

{% block content %}

	<h1>Update lease for {{ apartment }}</h1>
	<form method="POST" style="width:50%">

		{% csrf_token %}

		{{ acceptform.as_p }}

		{% if not updated_already %}
			<div id="accepted_inputs">
				{{ termform.as_p }}

				<p id="rent_sum"><strong>Monthly rent on this term: </strong></p>

				{{ garageform.as_p }}
			</div>
		{% endif %}

        <p><button type="submit" class="btn btn-xl btn-success" id="submit_button">Update</button><a href="/" class="btn btn-xl btn-warning" style="margin-left:1em">Cancel</a></p>


        {% if updated_already %}
			<p id="updated_already_message" style="color:#A65043"><strong>Contract conditions were updated already</strong></p>

		{% endif %}

	</form>

{% endblock %}